
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 19 20:12:02 CST 2018
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Verde = 8;
  public static final int cadena = 20;
  public static final int Morado = 9;
  public static final int coma = 12;
  public static final int resPanel = 2;
  public static final int Rojo = 4;
  public static final int Naranja = 7;
  public static final int corC = 17;
  public static final int igual = 18;
  public static final int corA = 16;
  public static final int EOF = 0;
  public static final int Negro = 11;
  public static final int Dibujar = 3;
  public static final int Azul = 5;
  public static final int Blanco = 10;
  public static final int error = 1;
  public static final int parC = 15;
  public static final int parA = 14;
  public static final int entero = 19;
  public static final int dosPuntos = 13;
  public static final int Amarillo = 6;
  public static final int iden = 21;
}

