
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 07 17:14:06 CST 2018
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Oeste = 3;
  public static final int coma = 6;
  public static final int Este = 5;
  public static final int parC = 9;
  public static final int Norte = 2;
  public static final int cadena = 11;
  public static final int parA = 8;
  public static final int Sur = 4;
  public static final int iden = 12;
  public static final int EOF = 0;
  public static final int entero = 10;
  public static final int error = 1;
  public static final int dosPuntos = 7;
}

