
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 13 08:06:21 CST 2018
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int bool = 56;
  public static final int resIf = 13;
  public static final int mul = 28;
  public static final int resVoid = 24;
  public static final int resProtected = 5;
  public static final int dosPuntos = 40;
  public static final int mayorq = 33;
  public static final int puntoYcoma = 39;
  public static final int resReturn = 22;
  public static final int resElse = 14;
  public static final int coma = 38;
  public static final int igual = 35;
  public static final int resSwitch = 18;
  public static final int resPrivate = 3;
  public static final int resImport = 2;
  public static final int caracter = 58;
  public static final int menorIgual = 32;
  public static final int decre = 49;
  public static final int iden = 57;
  public static final int resContinue = 20;
  public static final int resPublic = 4;
  public static final int menos = 27;
  public static final int EOF = 0;
  public static final int resString = 9;
  public static final int mas = 26;
  public static final int menorq = 31;
  public static final int mayorIgual = 34;
  public static final int error = 1;
  public static final int resChar = 10;
  public static final int resClass = 6;
  public static final int entero = 53;
  public static final int or = 51;
  public static final int resDo = 17;
  public static final int resBoolean = 8;
  public static final int punto = 47;
  public static final int resCase = 19;
  public static final int llaveC = 46;
  public static final int incre = 48;
  public static final int llaveA = 45;
  public static final int resBreak = 21;
  public static final int igualIgual = 36;
  public static final int diferente = 37;
  public static final int not = 52;
  public static final int and = 50;
  public static final int resInt = 7;
  public static final int parC = 42;
  public static final int resDouble = 11;
  public static final int parA = 41;
  public static final int resFor = 15;
  public static final int corC = 44;
  public static final int resDefault = 23;
  public static final int corA = 43;
  public static final int div = 29;
  public static final int resStatic = 25;
  public static final int resWhile = 16;
  public static final int decimal = 54;
  public static final int modulo = 30;
  public static final int cadena = 55;
  public static final int resObject = 12;
}

